POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1c3NpIiwiaWQiOiI2NzcyYmZmMWNjYjYwNmIzZDc1OTRjMjkiLCJpYXQiOjE3MzU1Nzg4NTl9.3BPvPLaae8BjK9UpWMijf4brGMH0tfE3QRXfd6PM37Q

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 69
}
